general:
  seed: 2025
  algorithm: pocar
  exp_dir: ./experiments
  n_seeds: 1
  env_name: "yu2022"

environment:
  partial_observation: true
  ep_timesteps: 2000
  omega: 0.0
  mu_type: "qualification"

algorithm:
  train_timesteps: 500_000
  eval_timesteps: 50_000
  ad_reg: "pocar"
  learning_rate: 1e-5


policy:
  use_predictor: false
  activation_fn: ReLU
  net_arch:
    - 256
    - 256
    - vf: [256, 128]
      pi: [256, 128]