general:
  seed: 2025
  algorithm: ppo
  exp_dir: ./experiments
  n_seeds: 1
  env_name: "yu2022"

environment:
  partial_observation: true
  ep_timesteps: 2000
  omega: 0.0
  mu_type: "qualification"

algorithm:
  policy: MlpPolicy
  learning_rate: 1e-5
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  train_timesteps: 2_000
  eval_timesteps: 10_000

policy:
  activation_fn: ReLU
  net_arch:
    - 256
    - 256
    - vf: [256, 128]
      pi: [256, 128]