name: sellf_censored_25
algorithm_param_list : [
  {"beta_1": 1, "beta_2": 0.01, "censor" : 0.25},
  {"beta_1": 2, "beta_2": 0.01, "censor" : 0.25},
  {"beta_1": 5, "beta_2": 0.01, "censor" : 0.25},
  {"beta_1": 10, "beta_2": 0.01,"censor" : 0.25},
  {"beta_1": 1, "beta_2": 0.05,"censor" : 0.25},
  {"beta_1": 2, "beta_2": 0.05,"censor" : 0.25},
  {"beta_1": 5, "beta_2": 0.05,"censor" : 0.25},
  {"beta_1": 10, "beta_2": 0.05,"censor" : 0.25},
  {"beta_1": 1, "beta_2": 0.1,"censor" : 0.25},
  {"beta_1": 2, "beta_2": 0.1,"censor" : 0.25},
  {"beta_1": 5, "beta_2": 0.1,"censor" : 0.25},
  {"beta_1": 10, "beta_2": 0.1,"censor" : 0.25},
]