name: sellf_censored
algorithm_param_list : [
  {"beta_1": 5, "beta_2": 0.01, "censor" : 0.},
  {"beta_1": 5, "beta_2": 0.01, "censor" : 0.1},
  {"beta_1": 5, "beta_2": 0.01, "censor" : 0.2},
  {"beta_1": 5, "beta_2": 0.01, "censor" : 0.3},
  {"beta_1": 5, "beta_2": 0.01, "censor" : 0.4},
  {"beta_1": 5, "beta_2": 0.01, "censor" : 0.5},
]