name: sellf
algorithm_param_list : [
  {"beta_1": 1, "beta_2": 0.01,},
  {"beta_1": 2, "beta_2": 0.01,},
  {"beta_1": 3, "beta_2": 0.01,},
  {"beta_1": 4, "beta_2": 0.01,},
  {"beta_1": 5, "beta_2": 0.01,},
  {"beta_1": 10, "beta_2": 0.01,},
]